language: python
python:
  - '3.6'
install:
  - pip install pipenv --upgrade && pipenv install --dev
script:
  - pipenv run flake8
  - pipenv run mypy .
  - ./test
services:
  - postgresql
before_script:
  - ./tools/create-tables
env:
  - ENVIRONMENT=testing
