sudo: required
language: python
services:
  - docker
python:
  - '3.6'
before_install:
  - docker pull zackhsi/boggle:latest
  - ./build --cache-from zackhsi/boggle:latest
before_script:
  - docker run --detach --name postgres postgres
  - ./run ./tools/create-tables
script:
  - ./run pipenv run flake8
  - ./run pipenv run mypy .
  - ./run ./test
env:
  - ENVIRONMENT=testing
