sudo: required
language: python
services:
  - docker
python:
  - '3.6'
env:
  - ENVIRONMENT=testing
branches:
  only:
    - master
before_install:
  - docker pull zackhsi/boggle:latest
  - ./build --cache-from zackhsi/boggle:latest
before_script:
  - ./run ./tools/create-tables
script:
  - ./run pipenv run flake8
  - ./run pipenv run mypy .
  - ./run ./test
after_success:
  - if [[ "${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}" == "master" ]]; then
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
      docker tag zackhsi/boggle:master zackhsi/boggle:latest;
      docker push zackhsi/boggle:latest;
    fi
